### PR TITLE
Enforce duration unit ordering

### PR DESCRIPTION
**Pull request by juliusv**
This actually even found a bug in my test duration :)

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@Nexucis

**Comment by Nexucis** [comment]
It won't be cleared to do it using an external token ? The regexp is a bit not digest :/

**Comment by Nexucis** [comment]
btw if you want me to review the PR, you can just request the review ^^. Like that you don't have to highlight me each time manually.

**Comment by juliusv** [comment]
@Nexucis I added a comment, hopefully that will be clearer with it :) I'd like to avoid custom code if it doesn't get even more complex than that...

**Comment by juliusv** [comment]
> btw if you want me to review the PR, you can just request the review ^^. Like that you don't have to highlight me each time manually.

Yep did that now, it didn't autosuggest you, so meh :)

**Comment by Nexucis** [comment]
> Yep did that now, it didn't autosuggest you, so meh :)

lol no issue, it was just a suggestion ^^

> This actually even found a bug in my test duration :)

Wouldn't be worth to have a test that checks it's actually failed when it is not correct ?

**Comment by Nexucis** [comment]
> @Nexucis I added a comment, hopefully that will be clearer with it :) I'd like to avoid custom code if it doesn't get even more complex than that...

Yeah it's fine. I think the less we are using the token, the better it is. So yeah good thing you did it using only the grammar

**Comment by juliusv** [comment]
> Wouldn't be worth to have a test that checks it's actually failed when it is not correct ?

At first I thought this wasn't possible because the tester just errored out with a parse error when providing an invalid input expression. But it seems when you do provide an expected output that contains an error node, you can actually create these negative tests after all. I added one for a case of bad unit ordering.

**Comment by Nexucis** [comment]
nice ! LGTM.

**Pull request merged**
